name: Daily XRP-EUR Report

on:
  schedule:
    # Runs at 05:00 UTC daily (07:00 AM CEST)
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
 contents: write

jobs:
  build-and-send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          COINBASE_API_KEY: ${{ secrets.COINBASE_API_KEY }}
          COINBASE_API_SECRET: ${{ secrets.COINBASE_API_SECRET }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          PURCHASE_PRICES: ${{ secrets.PURCHASE_PRICES }}
        run: python report.py

      - name: Commit and push updated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add historical_data.csv weekly_report_graph.png
          # Commit only if there are changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "feat: update daily report and graph" && git push)
